### ISSUE TITLE
when running; it shows a small indication on the screen

### ISSUE THREAD

**Issue by iptvcld** [adrianlungu/ScreenSleep#2]
when running; it shows a small indication on the screen - can we take the off?

**Comment by adrianlungu** [comment]
Hello there,

Could you post a screenshot as I'm not sure what you're referring to ?

**Comment by Bronexx** [comment]
Quando mexe o mouse ou algo do tipo ativa novamente, há a possibilidade de não voltar a ligar o monitor quando mexe no mouse ou teclado?

**Comment by adrianlungu** [comment]
@Bronexx what would be the use case for that ? 

If mouse or keyboard were disabled, what other way would you resume using the computer ?

**Comment by Bronexx** [comment]
@adrianlungu via acesso remoto, impossibilitando o usuário de mexer no pc e visualizar a tela.

**Comment by adrianlungu** [comment]
@Bronexx that may be possible, however, please open another issue for this as it's different from what this current issue is; and I may not have time right now to look further into it so feel free to contribute if this is urgent and something you need. 

You may also try to do something like this in combination with the app:
https://answers.microsoft.com/en-us/windows/forum/all/display-off-turn-on-only-with-keyboard-ignore/585c901f-4433-4561-bf4f-2ccfa1dbf4e8

**Comment by rmpel** [comment]
![2020-08-02 (2)_LI](https://user-images.githubusercontent.com/1086776/89126544-a8560e00-d4e6-11ea-8c05-feebab80dadc.jpg)
What iptvcld apparently has not done yet; I have the same issue, and here is it indicated in a screenshot.

When I use Process Explorer to "identify process" it clearly shows it's the ScreenSleep application.

There are more issues, like, the system tray popup menu staying on screen when I used it to sleep the display, the hot-key not working, but this one but this one is the most annoying.

**Comment by adrianlungu** [comment]
@rmpel thanks for the additional details, I'll take a look this week!

**Comment by chaphal3** [comment]
It appears to be the border and shadow of a window collapsed to a minimal number of pixels. This window can be stretched to show a white box by grabbing over it with your mouse, but not collapsed enough to completely hide the borders. Windows can disable the shadow, but I don't know how to disable the border from the user's end. 

![screensleepborders](https://user-images.githubusercontent.com/6118433/92422376-22635d80-f14b-11ea-914e-969a625531d3.jpg)

Note: ScreenSleep was in the foreground (brought to top by Alt+Tab) for each screenshot, making the border darker than in the example from rmpel.

**Comment by rmpel** [comment]
That is a great explanation for what is happening, and I guess there is not much that can be done about it. I'm not a Windows software developer, so maybe I'm saying something stupid here;
Why is there a window in the first place? the app is a system-tray-app, right? 
If the window is needed, is there a registry entry that can be altered to place the window on a negative position (as in; off-screen)?

In any case; thank you for your time and effort :)
