### ISSUE TITLE
Function Keys dont work as shortcut keys

### ISSUE THREAD

**Issue by godzillasushi** [adrianlungu/ScreenSleep#4]
Hi,
first thanks for this usefull app!

my problem is that F1 to F24 dont seem to work as shortcut keys to put the monitors to sleep.
the program registers the button press and sets it as shortcut, but it doesnt trigger the app for some reason.
works fine with the standard ctrl+shift+m and other keys

any idea what the problem could be?

![ScreenSleep_C5rh52VdrB](https://user-images.githubusercontent.com/13647274/99536165-47294c00-29aa-11eb-8405-94c9974e22ee.png)

**Comment by adrianlungu** [comment]
Hey!

I haven't tested it with the function keys, could be that there's a slightly different way of capturing KeyDown on these, I'll take a look!

**Comment by godzillasushi** [comment]
thanks for looking into this!

**Comment by adrianlungu** [comment]
It should now be fixed:

https://github.com/adrianlungu/ScreenSleep/releases/tag/1.0.5

**Comment by godzillasushi** [comment]
Thanks, it works now
Much appreciated!
