### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by cypres0099** [adrianlungu/ScreenSleep#5]
I'm a total newbie with this type of program, so I'm sure it's not really an issue with the application. I can't figure out how to install it. I've unzipped it, but none of the files will run when I click them. 

Do I have to unzip the folder to a specific location?

**Comment by adrianlungu** [comment]
Hello,

Do you get any kind of error or any message ? 

The application doesn't display anything when run, apart from a Tray icon on the bottom right with the `ScreenSleep` logo, i.e. ![](https://github.com/adrianlungu/ScreenSleep/raw/master/Images/taskbar.png)

If it doesn't show there, can you give me some additional information, i.e. what version of Windows you're on, and if  you're on 10, which build ?

**Comment by cypres0099** [comment]
I really don't think I completed the installation. I just downloaded the zip file then unzipped it to my documents folder. I figured I would either need to run an executable or place the folder in another folder that automatically runs at startup or something. I tried finding a file to run for installation but none of the files open on my computer correctly. 

Windows 10 Home

**Comment by adrianlungu** [comment]
After you unzip the archive, you should get 2 files:
```
ScreenSleep.exe
ScreenSleep.exe.config
```

You just need to run `ScreenSleep.exe`.

**Comment by cypres0099** [comment]
This is what I get when I unzip

![Capture](https://user-images.githubusercontent.com/74935762/100030829-feaecb80-2db9-11eb-834c-a58b2fc11dab.PNG)

**Comment by adrianlungu** [comment]
Ah, that's the source, you need the release binary from here:
https://github.com/adrianlungu/ScreenSleep/releases/download/1.0.4/ScreenSleep-1.0.4.7z

**Comment by cypres0099** [comment]
Ooops, sorry I forgot to thank you for the help. That download worked as expected and I'm up and running!  Thanks!
