### ISSUE TITLE
Keyboard shortcuts don't seem to work

### ISSUE THREAD

**Issue by adamscoble** [adrianlungu/ScreenSleep#7]
Hi there, I've tried a couple of different shortcuts (such as Ctrl+Alt+F12), but none of them seem to actually trigger the monitors sleeping. I have the timer set to 1 second, however I tried higher to see if maybe I was cancelling it out. I'm on the latest version of Windows 10. Apologies if I'm doing something silly!

**Comment by adrianlungu** [comment]
Hello,

It is possible that, if something else owns the specific shortcuts configured into ScreenSleep, they might not trigger sleep. 

Does CTRL + SHIFT + N not work either ?

**Comment by adamscoble** [comment]
Actually, strangely Ctrl + Alt + 2 still seems to work, even though it’s
set to Ctrl + Alt + F12

**Comment by adrianlungu** [comment]
Ah, which version are you on ? This used to be a bug that was fixed in 1.0.5

**Comment by adamscoble** [comment]
I’m on 1.0.5 apparently, at least that’s what the zip I installed from
tells me.

**Comment by adrianlungu** [comment]
I'll take a look, maybe there's more to it than was covered in 1.0.5!

**Comment by adamscoble** [comment]
Awesome, thanks! And thanks for the software!

**Comment by Thynix** [comment]
The default of Ctrl+Shift+M is working for me - do you have more information on the behavior you're seeing?

**Comment by adamscoble** [comment]
Hi Steve,

I have my shortcut set to Ctrl + Alt + F12 which doesn't work, however Ctrl
+ Alt + 2 *does. *Ctrl + Shift + M doesn't work for me (though it's not set
in the application so I wouldn't expect it to?). Is that what you mean?

**Comment by Thynix** [comment]
I can reproduce Ctrl + Alt + F12 not working. I suspect it may have something to do with F12 being treated differently?

**Comment by Thynix** [comment]
Oh, yeah, I meant does Ctrl + Shift + M work if you set it to.

**Comment by adrianlungu** [comment]
The issue with the function keys is that they are not properly translated into the code that is stored, so the combination is not recognized afterwards thus not triggering the sleeping effect.

I'm not that often on Windows these days so I haven't had a chance to look too much into it but will probably have an update of some sort soon.

**Comment by adamscoble** [comment]
Awesome, thanks @adrianlungu!
